# Generated by Django 6.1 on 2026-09-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0003_conversation_chatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="account_deletions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-deleted_at"],
            },
        ),
    ]
